
services:
  mongo_db:
    image: mongo:latest
    container_name: mongo_db
    restart: always   
    volumes:
      - mongo_db:/data/db


  app:
    build: .
    container_name: app
    restart: always
    ports:
      - "3000:3000"
    environment:
      - APP_NAME=app
      - PORT=3000
      - MONGO_URI=mongodb://mongo_db:27017/flickerImageDB
    depends_on:
      - mongo_db    
volumes:
  mongo_db: {}